trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
pr: none
  
jobs:
  - job: Base
    strategy:
      matrix:
        x86:
          poolImageName: 'Azure Pipelines'
          imageNameSuffix: 'x86'
        armv7l:
          poolImageName: 'build-farm-rpi4'
          imageNameSuffix: 'armv7l'
    pool: $(poolImageName)
    variables:
      imageName: 'edgeworx/darcy-ai-base-$(imageNameSuffix)'
      imageTag: 'dev'
    steps:
      - script: |
          RELEASE_TAG=$(git describe --tags --abbrev=0)
          echo "##vso[task.setvariable variable=imageTag]$RELEASE_TAG"
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      - template: ./docker-task-template.yml
        parameters:
          imageName: $(imageName)
          imageTag: $(imageTag)
          dockerFile: 'base/Dockerfile'

  - job: Coral
    dependsOn: Base
    strategy:
      matrix:
        x86:
          poolImageName: 'Azure Pipelines'
          imageNameSuffix: 'x86'
        armv7l:
          poolImageName: 'build-farm-rpi4'
          imageNameSuffix: 'armv7l'
    pool: $(poolImageName)
    variables:
      imageName: 'edgeworx/darcy-ai-coral-$(imageNameSuffix)'
      imageTag: 'dev'
    steps:
      - script: |
          RELEASE_TAG=$(git describe --tags --abbrev=0)
          echo "##vso[task.setvariable variable=imageTag]$RELEASE_TAG"
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      - template: ./docker-task-template.yml
        parameters:
          imageName: $(imageName)
          imageTag: $(imageTag)
          dockerFile: 'coral/Dockerfile'
