trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
pr: none
  
jobs:
  - job: DarcyAIDockerImages

    timeoutInMinutes: 240
  
    strategy:
      matrix:
        x86:
          poolImageName: 'Azure Pipelines'
          imageNameSuffix: 'x86'
        armv7l:
          poolImageName: 'RPi'
          imageNameSuffix: 'armv7l'

    pool: $(poolImageName)

    variables:
      imageName: 'edgeworx/darcy-ai'
      imageTag: 'dev'

    steps:
      - script: |
          RELEASE_TAG=$(git describe --tags --abbrev=0)
          echo "##vso[task.setvariable variable=imageTag]$RELEASE_TAG"
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        displayName: 'Set image tag'

      - template: ./docker-task-template.yml
        parameters:
          imageName: '$(imageName)-base-$(imageNameSuffix)'
          imageTag: $(imageTag)
          dockerFile: 'base/Dockerfile'
          imageNameSuffix: '$(imageNameSuffix)'
          step: 'base'

      - template: ./docker-task-template.yml
        parameters:
          imageName: '$(imageName)-coral-$(imageNameSuffix)'
          imageTag: $(imageTag)
          dockerFile: 'coral/Dockerfile'
          imageNameSuffix: '$(imageNameSuffix)'
          step: 'coral'
