trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
pr: none
  
timeoutInMinutes: 240

strategy:
  matrix:
    base:
      step: base
    coral:
      step: coral
    cpu:
      step: cpu

pool: 'Azure Pipelines'

variables:
  DOCKER_CLI_EXPERIMENTAL: enabled
  imageName: 'darcyai/darcy-ai'
  imageTag: 'dev'

steps:
- script: |
    RELEASE_TAG=$(git describe --tags --abbrev=0)
    echo "##vso[task.setvariable variable=imageTag]$RELEASE_TAG"
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  displayName: 'Set image tag'

- script: |
    sudo apt-get install -y qemu-user-static
    sudo apt-get install -y binfmt-support
    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  displayName: 'Install prerequisites'

- template: ./docker-task-template.yml
  parameters:
    imageName: '$(imageName)-$(step)'
    imageTag: $(imageTag)
    dockerFile: '$(step)/Dockerfile'
    step: $(step)

- script: |
    docker run --rm \
      -v $(pwd)/tests:/src \
      $(imageName)-$(step):$(imageTag) \
      sh -c "cd /src && python3 -m pip install darcyai && python3 -u $(step).py"
  displayName: 'Test $(step) docker image'
